### ISSUE TITLE
Does anyone manage to run this locally?

### ISSUE THREAD

**Issue by vikkio88** [fyne-io/developer.fyne.io#128]
### Description
I have been trying to run this as the instruction suggest in my ubuntu with ruby 3.2 and using the docker image of `jekyll` and I am getting loads of issues:

on docker:
```
devfyne-jekyll | Configuration file: /site/_config.yml
devfyne-jekyll |   Dependency Error: Yikes! It looks like you don't have jekyll-redirect-from or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-redirect-from' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
devfyne-jekyll | jekyll 3.9.0 | Error:  jekyll-redirect-from
devfyne-jekyll | /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/external.rb:68:in `rescue in block in require_with_graceful_fail': jekyll-redirect-from (Jekyll::Errors::MissingDependencyException)
```

on my local ubuntu:
```
Incremental build: disabled. Enable with --incremental
      Generating... 
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
                    done in 149.233 seconds.
jekyll 3.9.0 | Error:  no implicit conversion of Hash into Integer
/var/lib/gems/3.0.0/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read': no implicit conversion of Hash into Integer (TypeError)

```

**Comment by Jacalz** [comment]
I've had issues locally on Fedora 37 and 38 as well. Ruby does not seem work great across system configurations from my testing unfortunately.

**Comment by Jacalz** [comment]
I've had issues locally on Fedora 37 and 38 as well. Ruby does not seem work great across system configurations from my testing unfortunately.

**Comment by andydotxyz** [comment]
I suspect Jekyll is quite specific about the ruby it needs (or the dependencies it uses) and what is in the repo works for GitHub.
It also works for me - but that doesn't help you!
All I can suggest is to tweak the versions for something that works locally - maybe try a vanilla Jekyll project and see if you can get that working, and if so then copy the versions or Gemfile over from there?

**Comment by vikkio88** [comment]
I did that and did not work either, I suspect it is what you say, there is
a way to lock in the ruby version using rvm seems like, might give that a go

**Comment by Jacalz** [comment]
We do have a container for building over at https://github.com/fyne-io/fyne-io.github.io/blob/master/README.md. It might be helpful but I haven't used it.

**Comment by vikkio88** [comment]
ah nice one, I tried to use the jekyll official one and did not work, might
try those

**Comment by vikkio88** [comment]
tried this and I got this error
```
 sh build.sh serve
Unable to find image 'jekyll/jekyll:3.8' locally
3.8: Pulling from jekyll/jekyll
9d48c3bd43c5: Pull complete 
9ce9598067e7: Pull complete 
278f4c997324: Pull complete 
bfca09e5fd9a: Pull complete 
2612f15b9d22: Pull complete 
322c093d5418: Pull complete 
Digest: sha256:9521c8aae4739fcbc7137ead19f91841b833d671542f13e91ca40280e88d6e34
Status: Downloaded newer image for jekyll/jekyll:3.8
Fetching gem metadata from https://rubygems.org/.........
nokogiri-1.14.3-x86_64-linux requires ruby version >= 2.7, < 3.3.dev, which is incompatible with the current version, ruby 2.6.3p62
```

seems like I am doomed

**Comment by andydotxyz** [comment]
I ran a full update as suggested and committed the result - Ruby 3 is now supported and tested locally
